### PR TITLE
Fix dyn in trait definition

### PR DESCRIPTION
**Pull request by justanotherdot**
Random rustfmt stuff floating about, too.

### CODE REVIEW

**Comment by BartMassey** [comment]
Thanks for pointing this out! I cleaned up the `rustfmt` and `clippy` stuff and added the missing `dyn` in patches 12faa3b 30feccc 36e304b just now.

**Comment by justanotherdot** [comment]
Sorry for the random opening and thanks for the patches! 

Have been fishing around for lazy vectors for use over in https://github.com/justanotherdot/rust-hedgehog/. I'm after something that will slip in easily with the existing code and I wonder if `SIVec` would do the job if it had an `Iterator` instance.

**Comment by BartMassey** [comment]
Wow, Hedgehog looks neat. Eager to see it done and documented so it can eat all my bugs.

The `Iterator` instance would be fairly trivial if you were willing to accept random ordering, but I think it would require sorting the indices of the stored entries if you wanted to traverse in order.

Honestly, my crate as it stands is likely to be both slow and buggy. I'd probably think thrice before folding it into anything. I think you'd be taking on a substantial maintenance burden.

Are there things a `BTreeMap<usize,T>` won't do for you?

**Comment by justanotherdot** [comment]
That port is largely done, but the problem I'm having is that `sequence` and friends in `shrink.rs` try to evaluate the whole tree at once, because the children aren't lazy. A lot of the other hedgehog ports simply use lazy lists for their rose tree implementations. If I could find a fleshed out implementation for that I might be good to go (I was going to try this next: https://github.com/reem/rust-lazylist). Mostly just trying not to write it myself first  😄 

It's interesting because you _could_ just use a boxed trait like Iterator but that actually winds up being clunky to slip in. The `BTreeMap<usize, T>` approach you mention, that's in relation to the same lazy-loading approach `SIVec` would take (trying to read up more on your inline docs to get a sense of how the data structure works)?

**Comment by BartMassey** [comment]
I think the `BTreeMap<usize, T>` will do everything `SIVec` would do and also provide efficient access to its contents ordered by index. *Technically* it will be log_B-time instead of constant-time access to a particular element, but in practice my thing is likely to be much slower on feasible-sized lists.

**Comment by BartMassey** [comment]
LOL. Realized I could use a `BTreeMap` as an oracle for some random testing. Uncovered a pretty severe bug almost immediately. :sweat_smile:  Fixed now.

Also bumped the crate to 2018 edition. I was confused by some of the error messages I was getting for the longest time… :slightly_smiling_face: 

Anyway, it's much cleaned up now — and still probably buggy and not ready for prime time. See my new issue #4 in particular.

**Comment by justanotherdot** [comment]
Nice on the cleanup! And thanks for the chatter

**Pull request closed without merging**
